// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arqddfzpvchclhpghcdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFycWRkZnpwdmNoY2xocGdoY2RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0OTI5MTgsImV4cCI6MjA1ODA2ODkxOH0.w94trqr-DbFAxYSP-TOyYguCnWs1RuO4Z53mmkx8FZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);